lib/teacher_web/router.ex
defmodule TeacherWeb.Router do
  use TeacherWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Teacher.Plugs.SetAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TeacherWeb do
    pipe_through :browser # Use the default browser stack

    get "/", AlbumController, :index
    resources "/albums", AlbumController
    resource "/sessions", SessionsController, only: [:new, :create]
    delete "/sign-out", SessionController, :delete
    resource "/registrations", RegistrationController, only: [:new, :create]
    resources "/purchases", PurchaseController, only: [:create]

    resource "/customers", CustomerController, only: [:show] do
      resource "/receipt", PurchaseController, :only: [:index, :show]
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", TeacherWeb do
  #   pipe_through :api
  # end
end

lib/teacher_web/views/layout_view.ex
defmodule TeacherWeb.LayoutView do
  use TeacherWeb, :view
end

lib/teacher_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Teacher!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= link "Home", to: album_path(@conn, :index) %> |
        <%= if signed_in?(@conn) do %>
          <%= link "Order History", to: customer_receipt_path(@conn, :index, @current_customer) %>
          <%= link "Sign out", to: session_path(@conn, :delete), method: :delete %>
        <% else %>
          <%= link "Sign In", to: session_path(@conn, :new) %>
          |
          <%= link "Sign up", to: registration_path(@conn, :new) %>
        <% end %>
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>