lib/teacher_web/router.ex
defmodule TeacherWeb.Router do
  use TeacherWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Teacher.Plugs.SetAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TeacherWeb do
    pipe_through :browser # Use the default browser stack

    get "/", AlbumController, :index
    resources "/albums", AlbumController
    resource "/sessions", SessionsController, only: [:new, :create]
    delete "/sign-out", SessionController, :delete
    resource "/registrations", RegistrationController, only: [:new, :create]
    resources "/purchases", PurchaseController, only: [:create]

    resource "/customers", CustomerController, only: [:show] do
      resource "/receipt", PurchaseController, :only: [:index, :show]
    end

  end

  # Other scopes may use custom stacks.
  # scope "/api", TeacherWeb do
  #   pipe_through :api
  # end
end

lib/teacher/records/album.ex
defmodule Teacher.Records.Album do
  use Ecto.Schema
  import Ecto.Changeset
  alias Teacher.Records.Album


  schema "albums" do
    field :artist, :string
    field :summary, :string
    field :title, :string
    field :year, :string
    field :price, :integer
    has_many :customers, Teacher.Purchases.Customer

    timestamps()
  end

  @doc false
  def changeset(%Album{} = album, attrs) do
    album
    |> cast(attrs, [:title, :summary, :year, :genre, :price])
    |> validate_required([:title, :summary, :year, :genre, :price])
  end
end

lib/teacher_web/controllers/album_controller.ex
defmodule TeacherWeb.AlbumController do
  use TeacherWeb, :controller

  alias Teacher.Records
  alias Teacher.Records.Album

  def index(conn, _params) do
    albums = Records.list_albums()
    render(conn, "index.html", albums: albums)
  end

  def new(conn, _params) do
    changeset = Records.change_album(%Album{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"album" => album_params}) do
    case Records.create_album(album_params) do
      {:ok, album} ->
        conn
        |> put_flash(:info, "Album created successfully.")
        |> redirect(to: album_path(conn, :show, album))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    album = Records.get_album!(id)
    render(conn, "show.html", album: album)
  end

  def edit(conn, %{"id" => id}) do
    album = Records.get_album!(id)
    changeset = Records.change_album(album)
    render(conn, "edit.html", album: album, changeset: changeset)
  end

  def update(conn, %{"id" => id, "album" => album_params}) do
    album = Records.get_album!(id)

    case Records.update_album(album, album_params) do
      {:ok, album} ->
        conn
        |> put_flash(:info, "Album updated successfully.")
        |> redirect(to: album_path(conn, :show, album))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", album: album, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    album = Records.get_album!(id)
    {:ok, _album} = Records.delete_album(album)

    conn
    |> put_flash(:info, "Album deleted successfully.")
    |> redirect(to: album_path(conn, :index))
  end
end

lib/teacher_web/views/album_view.ex
defmodule TeacherWeb.AlbumView do
  use TeacherWeb, :view


end

lib/teacher_web/templates/album/edit.html.eex
<h2>Edit Record</h2>

<%= render "form.html", Map.put(assigns, :action, album_path(@conn, :update, @album)) %>

<span><%= link "Back", to: album_path(@conn, :index) %></span>

lib/teacher_web/templates/album/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :summary, class: "control-label" %>
    <%= textarea f, :summary, class: "form-control" %>
    <%= error_tag f, :summary %>
  </div>

  <div class="form-group">
    <%= label f, :year, class: "control-label" %>
    <%= number_input f, :year, class: "form-control" %>
    <%= error_tag f, :year %>
  </div>

  <div class="form-group">
    <%= label f, :genre, class: "control-label" %>
    <%= text_input f, :genre, class: "form-control" %>
    <%= error_tag f, :genre %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/teacher_web/templates/album/index.html.eex
<h2>Vinyl Record Store</h2>

<table class="table">
  <thead>
    <tr>
      <th>Artist</th>
      <th>Title</th>
      <th>Summary</th>
      <th>Year</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= for album <- @albums do %>
      <tr>
        <td><%= album.artist %></td>
        <td><%= album.title %></td>
        <td><%= album.summary %></td>
        <td><%= album.year %></td>
        <td><%= cents_to_dollars(album.price) %></td>
        <td>
          <%= form_for @conn, purchase_path(@conn, :create, album_id: album.id), [method: :post], fn f -> %>
          <form action="/purchases" method="POST">
            <script
              src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="pk_test_YOUR_KEY"
              data-name="Record Store"
              data-description="Purchase <%= album.title %>"
              data-shipping-address="true"
              data-billing-address="true"
              data-label="Buy"
              data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
              data-locale="auto">
            </script>
            <% end %>
            </form>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

lib/teacher_web/templates/album/new.html.eex
<h2>New Record</h2>

<%= render "form.html", Map.put(assigns, :action, album_path(@conn, :create)) %>

<span><%= link "Back", to: album_path(@conn, :index) %></span>

lib/teacher_web/templates/album/show.html.eex
<h2>Show Record</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @album.title %>
  </li>

  <li>
    <strong>Summary:</strong>
    <%= @album.summary %>
  </li>

  <li>
    <strong>Year:</strong>
    <%= @album.year %>
  </li>

  <li>
    <strong>Genre:</strong>
    <%= @album.genre %>
  </li>

</ul>

<span><%= link "Edit", to: album_path(@conn, :edit, @album) %></span>
<span><%= link "Back", to: album_path(@conn, :index) %></span>